const candidates = [
  {name:'Nok',age:34,photo:'assets/nok.svg',location:'Bangkok · 25 min away',available:'Oct 1',fit:94,salary:'฿22,000–25,000',reason:'Infant specialist, within budget, familiar with international families.',facts:[['◎','Infant care','6 years'],['♧','Languages','Thai · English'],['♡','First aid','Certificate valid'],['⌂','References','2 of 2 verified']],skills:['0–12 month infant care','Baby CPR & first aid','Safe sleep practice','Feeding & sterilising','Daily care log'],preferences:'Live-out roles · Monday–Friday · Child-related duties · Comfortable with pets · No overnight shifts',quote:'Nok was calm, safety-conscious and wonderfully consistent with our daughter for nearly three years.'},
  {name:'Mali',age:39,photo:'assets/mali.svg',location:'Bangkok · 18 min away',available:'Sep 25',fit:91,salary:'฿24,000–27,000',reason:'Newborn experience, excellent stability, and strong English communication.',facts:[['◎','Newborn care','8 years'],['♧','Languages','Thai · English'],['♡','First aid','Certificate valid'],['⌂','References','3 of 3 verified']],skills:['Newborn routines','Baby CPR & first aid','Breastmilk handling','Sleep tracking','Postpartum support'],preferences:'Live-out or live-in · Weekdays · Newborn and infant care · Occasional evening work',quote:'Mali brought structure to our first months as parents while always respecting how we wanted to care for our baby.'},
  {name:'Pim',age:31,photo:'assets/pim.svg',location:'Bangkok · 32 min away',available:'Oct 8',fit:87,salary:'฿20,000–23,000',reason:'Warm developmental play style, flexible schedule, and well within budget.',facts:[['◎','Toddler care','5 years'],['♧','Languages','Thai · Basic English'],['♡','First aid','Course completed'],['⌂','References','2 of 2 verified']],skills:['Infant & toddler care','Developmental play','Baby-led feeding','Child-related cooking','Daily care log'],preferences:'Live-out roles · Flexible weekdays · Child-related cooking · Comfortable with one pet',quote:'Pim is energetic, affectionate and very good at turning ordinary routines into playful learning.'}
];
let index=0; let saved=new Set();
let pendingInterview=null;
const $=s=>document.querySelector(s);
const defaultPrompt='We live in Thong Lo and have an 8-month-old baby. We both work, so we need a live-out nanny Monday to Friday, 8am to 6pm. She should have infant experience, know first aid and speak a little English. Child-related cleaning only, no full-house cleaning. We have a cat and may need help in the evening twice a month.';
const helperExample='I have 6 years of childcare experience, mainly caring for babies and toddlers aged 0–3. I worked with two families and stayed with one family for 3 years. I can prepare children’s meals, sterilise bottles and keep a daily care log. I speak Thai and conversational English. I am looking for a live-out role in Bangkok, Monday to Friday, with child-related duties only.';
const mockHelpers=[{name:'Nok',photo:'assets/nok.svg'},{name:'Mali',photo:'assets/mali.svg'},{name:'Pim',photo:'assets/pim.svg'}];
let mockHelperIndex=0;
let currentBrief={};
function parsePrompt(text){
  const lower=text.toLowerCase();
  const chinese=/[\u3400-\u9fff]/.test(text);
  const age=(text.match(/(\d+)\s*(?:month|months|个月|月大)/i)||[])[1]||'8';
  const location=(text.match(/(?:live in|住在|位于)\s+([A-Za-z ]+?)(?:\s+and|，|,|。|\.|$)/i)||[])[1]?.trim() || (lower.includes('thong lo')?'Thong Lo':'Bangkok');
  const explicitlyLiveOut=lower.includes('live-out')||text.includes('不住家')||text.includes('非住家');
  const live=explicitlyLiveOut?'Live-out':(lower.includes('live-in')||text.includes('住家')?'Live-in':'Live-out');
  const schedule=lower.includes('monday')||text.includes('周一')?'Mon–Fri · 08:00–18:00':'Weekdays · Full-time';
  const language=lower.includes('english')||text.includes('英语')?'Thai + conversational English':'Thai';
  const duties=lower.includes('no full')||text.includes('不需要全屋')||text.includes('不做全屋')?'Child-related duties only':'Childcare + light household duties';
  const pet=lower.includes('cat')||text.includes('猫')?'Comfortable with a cat':lower.includes('dog')||text.includes('狗')?'Comfortable with a dog':'No pet preference stated';
  currentBrief={age:`${age}-month-old baby`,location,live,schedule,language,duties,pet,experience:'Infant care + first aid',source:text,detectedLanguage:chinese?'Chinese':'English'};
  return currentBrief;
}
function setStep(n){document.querySelectorAll('#onboarding .step').forEach((s,i)=>{s.classList.toggle('active',i===n-1);s.classList.toggle('done',i<n-1);if(i<n-1)s.querySelector('span').textContent='✓';else s.querySelector('span').textContent=i+1})}
function setHelperStep(n){document.querySelectorAll('.helper-steps .step').forEach((s,i)=>{s.classList.toggle('active',i===n-1);s.classList.toggle('done',i<n-1);s.querySelector('span').textContent=i<n-1?'✓':i+1})}
function applyMockHelper(){const h=mockHelpers[mockHelperIndex%mockHelpers.length];$('#helperName').textContent=h.name;$('#helperPhoto').src=h.photo;$('#previewName').textContent=h.name;$('#previewPhoto').src=h.photo}
function resetFamilyFlow(){$('#promptScreen').hidden=false;$('#briefScreen').hidden=true;$('#carePrompt').value=defaultPrompt;$('#charCount').textContent=defaultPrompt.length;setStep(1);$('#onboarding').scrollTop=0}
function resetHelperFlow(){$('#helperConnect').hidden=false;$('#helperExperience').hidden=true;$('#helperReview').hidden=true;setHelperStep(1);$('#helperOnboarding').scrollTop=0}
function showBrief(){
  const text=$('#carePrompt').value.trim(); if(!text){toast('Tell us a little about your family first');return}if(/chiang mai|phuket|pattaya|hua hin|清迈|普吉|芭提雅/i.test(text)){toast('Kinderly is currently available in Bangkok only');return}
  const b=parsePrompt(text);$('#originalPrompt').textContent=text;
  const items=[['♡','Who needs care',b.age,'A little one at home'],['⌖','Where you are',b.location,'Your neighbourhood'],['⌂','Care setup',b.live,'The arrangement you prefer'],['◷','Your usual week',b.schedule,'When support matters'],['文','Communication',b.language,'Languages that work for you'],['✦','What feels important',b.experience,'Experience you value'],['✓','A clear role',b.duties,'What the nanny will handle'],['♧','Life at home',b.pet,'Helpful to know before matching']];
  $('#briefGrid').innerHTML=items.map(([icon,label,value,note])=>`<button class="brief-item" type="button"><span class="brief-symbol">${icon}</span><span class="brief-copy"><small>${label}</small><b>${value}</b><em>${note}</em></span><span class="brief-edit" aria-hidden="true">✎</span></button>`).join('');
  $('#promptScreen').hidden=true;$('#briefScreen').hidden=false;setStep(2);$('#onboarding').scrollTo({top:0,behavior:'smooth'});
}
function render(){const c=candidates[index];$('#candidatePhoto').src=c.photo;$('#candidateName').textContent=c.name;$('#candidateAge').textContent=c.age;$('#candidateLocation').textContent=c.location;$('#activeStatus').textContent=['Active 12 min ago','Active 28 min ago','Active today'][index];$('#availableDate').textContent=c.available;$('#fitScore').textContent=c.fit;$('#fitReason').innerHTML=`<b>${index===0?'Strong match for your baby':'Why this match works'}</b><br>${c.reason}`;$('#salary').textContent=c.salary;$('#facts').innerHTML=c.facts.map(f=>`<div class="fact"><span class="fact-icon">${f[0]}</span><div><b>${f[1]}</b><span>${f[2]}</span></div></div>`).join('');$('#matchNumber').textContent=String(index+1).padStart(2,'0');$('#progressBar').style.width=`${(index+1)/candidates.length*100}%`;$('.privacy-note').textContent=`Your interest stays private until ${c.name} accepts your invitation.`;$('#bookmarkBtn').classList.toggle('saved',saved.has(index));$('#bookmarkBtn').textContent=saved.has(index)?'♥':'♡';}
function next(direction){const card=$('#candidateCard');card.classList.add(direction==='pass'?'out-left':'out-right');setTimeout(()=>{index=(index+1)%candidates.length;render();card.classList.remove('out-left','out-right')},220)}
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2300)}
function openProfile(){const c=candidates[index];$('#dialogPhoto').src=c.photo;$('#dialogName').textContent=`${c.name}, ${c.age}`;$('#dialogSubtitle').textContent=`Infant nanny · ${c.location.split(' · ')[0]}`;$('#dialogReason').textContent=c.reason;$('#skillList').innerHTML=c.skills.map(x=>`<span>✓ ${x}</span>`).join('');$('#preferences').textContent=c.preferences;$('#referenceQuote').textContent=c.quote;$('#profileDialog').showModal()}
function openInterview(){const c=candidates[index];$('#interviewCandidate').textContent=c.name;$('#inviteMessage').value='';$('#interviewDialog').showModal()}
function selectedTimes(){return [...document.querySelectorAll('.time-option.selected')].map(x=>x.dataset.time)}
function addNotification(name){$('#notificationDot').parentElement.classList.add('has-update');$('#notificationList').innerHTML=`<div class="notification-item"><span>⌁</span><div><p><b>Invitation sent to ${name}</b><br>We notified her in Kinderly and via LINE. Waiting for her response.</p><time>Just now</time><button id="simulateAcceptBtn">Simulate nanny accepting</button></div></div>`;$('#simulateAcceptBtn').onclick=simulateAccept}
function simulateAccept(){if(!pendingInterview)return;$('#notificationDot').parentElement.classList.add('has-update');$('#notificationList').innerHTML=`<div class="notification-item"><span>✓</span><div><p><b>${pendingInterview.name} accepted your invitation</b><br>Your interview is confirmed. Contact sharing is now available.</p><time>Just now</time><button id="viewMatchBtn">View interview</button></div></div>`;$('#viewMatchBtn').onclick=showMatch;showMatch()}
function showMatch(){if(!pendingInterview)return;$('#matchMessage').textContent=`${pendingInterview.name} chose one of your proposed times. You can now coordinate the call.`;$('#confirmedTime').textContent=pendingInterview.times[0];$('#confirmedMethod').textContent=pendingInterview.method;$('#notificationPanel').hidden=true;$('#matchDialog').showModal()}
function addCredits(points){$('#creditCount').textContent=Number($('#creditCount').textContent)+points}
$('#completeInterviewBtn').onclick=()=>{$('#matchDialog').close();$('#reportCandidate').textContent=`${pendingInterview.name} accepted and attended`;$('#reportTime').textContent=`Interview completed via ${pendingInterview.method}`;$('#interviewReportDialog').showModal()};
$('#submitInterviewReport').onclick=()=>{addCredits(100);$('#interviewReportDialog').close();$('#notificationDot').parentElement.classList.add('has-update');$('#notificationList').innerHTML=`<div class="notification-item"><span>✓</span><div><p><b>Interview report saved · +100 credits</b><br>${pendingInterview.name}: ${$('#interviewOutcome').value}. The result will improve future recommendations.</p><time>Just now</time><button id="workReportBtn">Simulate 30-day work check-in</button></div></div>`;$('#workReportBtn').onclick=()=>{$('#notificationPanel').hidden=true;$('#workReportDialog').showModal()};$('#notificationPanel').hidden=false;toast('Interview report saved · +100 credits')};
$('#submitWorkReport').onclick=()=>{addCredits(300);$('#workReportDialog').close();$('#notificationDot').parentElement.classList.add('has-update');$('#notificationList').innerHTML=`<div class="notification-item"><span>◉</span><div><p><b>30-day work report completed · +300 credits</b><br>A verified work-history checkpoint was added for both sides.</p><time>Just now</time></div></div>`;toast('Work check-in completed · +300 credits')};
function simple(title,body){$('#simpleDialogContent').innerHTML=`<h2>${title}</h2>${body}`;$('#simpleDialog').showModal()}
$('#passBtn').onclick=()=>next('pass');
$('#inviteBtn').onclick=openInterview;
$('#dialogInvite').onclick=()=>{$('#profileDialog').close();openInterview()};
$('#detailsBtn').onclick=openProfile;
$('#candidatePhoto').onclick=openProfile;
$('#bookmarkBtn').onclick=()=>{saved.has(index)?saved.delete(index):saved.add(index);render();toast(saved.has(index)?'Saved to your shortlist':'Removed from shortlist')};
$('#soundBtn').onclick=e=>{e.stopPropagation();toast(`${candidates[index].name}’s 45-second intro would play here`)};
$('#briefBtn').onclick=()=>simple('Your care brief','<p>One 8-month-old baby in Thong Lo. Monday–Friday, 8:00–18:00. Live-out. Infant care and child-related household tasks only.</p><ul><li>Budget: ฿20,000–27,000/month</li><li>Thai + conversational English</li><li>Infant experience and first aid required</li></ul>');
$('#creditBtn').onclick=$('#creditLearnBtn').onclick=()=>simple('Care Credits','<p>Earn credits for completing meaningful hiring steps—not for leaving a positive review.</p><ul><li>Paid trial completed: +200</li><li>Both sides leave feedback: +200 each</li><li>30-day check-in: +300</li></ul><p>Credits can reduce the cost of future verification, matching and training services. Nanny wages are always paid in real money.</p>');
$('#carePrompt').addEventListener('input',e=>{$('#charCount').textContent=e.target.value.length});
$('#exampleBtn').onclick=()=>{$('#carePrompt').value=defaultPrompt;$('#charCount').textContent=defaultPrompt.length;$('#carePrompt').focus()};
$('#blankBtn').onclick=()=>{$('#carePrompt').value='';$('#charCount').textContent='0';$('#carePrompt').focus()};
$('#understandBtn').onclick=showBrief;
$('#backBtn').onclick=()=>{$('#briefScreen').hidden=true;$('#promptScreen').hidden=false;setStep(1)};
$('#findMatchesBtn').onclick=()=>{currentBrief.budget=$('#budgetSelect').value;currentBrief.start=$('#startDate').value;$('#briefSummary').textContent=`${currentBrief.age} · ${currentBrief.location} · ${currentBrief.live}`;setStep(3);$('#onboarding').classList.add('hidden');setTimeout(()=>{$('#onboarding').hidden=true},360);toast('3 verified matches found')};
$('#voiceBtn').onclick=()=>toast('Voice input would start here');
$('#briefGrid').addEventListener('click',e=>{if(e.target.closest('.brief-item'))toast('Inline editing would open here')});
function updateJobStrength(){const fields=[...document.querySelectorAll('.condition-field')];const completed=fields.filter(x=>x.value!=='').length;const score=50+completed*8;$('#strengthScore').textContent=score;$('#strengthBar').style.width=`${score}%`;fields.forEach(x=>x.classList.toggle('completed',x.value!==''));const left=fields.length-completed;$('#visibilityHint').innerHTML=left?`<span>↗</span> Complete ${left} more ${left===1?'detail':'details'} to improve visibility.`:'<span>✓</span> Excellent transparency — eligible for a visibility boost.'}
document.querySelectorAll('.condition-field').forEach(x=>x.addEventListener('change',updateJobStrength));
updateJobStrength();
$('#familyRole').onclick=()=>{resetFamilyFlow();$('#roleGate').hidden=true;$('#onboarding').hidden=false};
$('#helperRole').onclick=()=>{resetHelperFlow();$('#roleGate').hidden=true;$('#onboarding').hidden=true;$('#helperOnboarding').hidden=false};
$('#switchRole').onclick=()=>{$('#helperOnboarding').hidden=true;$('#roleGate').hidden=false};
document.querySelectorAll('.social-logins button').forEach(btn=>btn.onclick=()=>{mockHelperIndex=Math.floor(Math.random()*mockHelpers.length);applyMockHelper();$('#providerName').textContent=btn.dataset.provider;$('#helperConnect').hidden=true;$('#helperExperience').hidden=false;$('#experiencePrompt').value=helperExample;$('#experienceCount').textContent=helperExample.length;setHelperStep(2);toast(`Mock ${btn.dataset.provider} profile imported`)});
$('#experiencePrompt').addEventListener('input',e=>{$('#experienceCount').textContent=e.target.value.length});
$('#helperBack1').onclick=()=>{$('#helperExperience').hidden=true;$('#helperConnect').hidden=false;setHelperStep(1)};
$('#randomizePhoto').onclick=()=>{mockHelperIndex=(mockHelperIndex+1)%mockHelpers.length;applyMockHelper();toast('Another mock profile photo imported')};
$('#helperVoice').onclick=()=>toast('Voice input would start here');
$('#buildProfileBtn').onclick=()=>{if(!$('#photoApproved').checked){toast('Approve this photo or choose another');return}$('#helperExperience').hidden=true;$('#helperReview').hidden=false;setHelperStep(3)};
$('#helperBack2').onclick=()=>{$('#helperReview').hidden=true;$('#helperExperience').hidden=false;setHelperStep(2)};
$('#finishHelperProfile').onclick=()=>{$('#helperReview').innerHTML='<div class="helper-success"><span>✓</span><p class="eyebrow">PROFILE SUBMITTED</p><h1>Ready for<br><em>the next step.</em></h1><p class="helper-lede">Your identity, references and skills can now be verified. You may receive interview invitations while work authorization is pending.</p><button class="continue-btn" onclick="location.reload()">Return to start</button></div>';setHelperStep(3)};
function updateHelperBoosters(){const uploads=[$('#videoUpload'),$('#referenceUpload')];const added=uploads.filter(x=>x.files.length).length;$('#helperStrength').textContent=80+added*10;$('#trustBoostCount').textContent=`${added} of 2 added`;uploads.forEach(x=>x.closest('.booster-card').classList.toggle('added',x.files.length>0));const evidence=document.querySelectorAll('.evidence-overview .trust-statuses span');if(evidence.length){evidence[4].textContent=uploads[0].files.length?'Video · provided':'Video · not added';evidence[5].textContent=uploads[1].files.length?'Reference · provided':'Reference · not added';evidence[4].className=uploads[0].files.length?'provided':'declared';evidence[5].className=uploads[1].files.length?'provided':'declared'}}
$('#videoUpload').addEventListener('change',()=>{updateHelperBoosters();if($('#videoUpload').files.length)toast('Introduction video added')});
$('#referenceUpload').addEventListener('change',()=>{updateHelperBoosters();if($('#referenceUpload').files.length)toast('Reference letter added')});
document.querySelector('.trust-boosters').insertAdjacentHTML('beforebegin','<div class="evidence-overview"><p><b>Your profile evidence</b><small>Families can see how each detail was sourced.</small></p><div class="trust-statuses"><span class="verified">Photo · verified</span><span class="declared">Experience · declared</span><span class="provided">Language · provided</span><span class="declared">Identity status · declared</span><span class="declared">Video · not added</span><span class="declared">Reference · not added</span></div></div>');
const languageCopy={en:{welcome:'WELCOME TO KINDERLY',title:'Care starts with<br><em>the right connection.</em>',side:'Tell us which side of the match you’re on.',family:'I’M A FAMILY',familyTitle:'Find a trusted nanny',familyText:'Describe your care needs and meet verified matches.',nanny:'I’M A NANNY',nannyTitle:'Build my professional profile',nannyText:'Show your experience, preferences and work status.',switchRole:'← Switch role',boost:'OPTIONAL TRUST BOOSTERS',boostTitle:'Help families feel confident sooner.',video:'Introduction video',reference:'Reference letter'},zh:{welcome:'欢迎来到 KINDERLY',title:'好的照护，始于<br><em>对的人。</em>',side:'请选择你在配对中的角色。',family:'我是家庭雇主',familyTitle:'寻找值得信赖的育儿帮手',familyText:'描述照护需求，认识经过筛选的合适人选。',nanny:'我是育儿帮手',nannyTitle:'建立专业个人档案',nannyText:'展示经验、工作偏好与工作状态。',switchRole:'← 切换角色',boost:'可选信任加分项',boostTitle:'让家庭更快建立信任。',video:'自我介绍影片',reference:'推荐信'},th:{welcome:'ยินดีต้อนรับสู่ KINDERLY',title:'การดูแลที่ดี เริ่มจาก<br><em>คนที่ใช่</em>',side:'เลือกบทบาทของคุณในการจับคู่',family:'ฉันคือครอบครัว',familyTitle:'ค้นหาพี่เลี้ยงที่ไว้ใจได้',familyText:'บอกความต้องการและพบผู้สมัครที่เหมาะสม',nanny:'ฉันคือพี่เลี้ยง',nannyTitle:'สร้างโปรไฟล์มืออาชีพ',nannyText:'แสดงประสบการณ์ ความต้องการ และสถานะการทำงาน',switchRole:'← เปลี่ยนบทบาท',boost:'เพิ่มความน่าเชื่อถือ',boostTitle:'ช่วยให้ครอบครัวมั่นใจได้เร็วขึ้น',video:'วิดีโอแนะนำตัว',reference:'จดหมายรับรอง'},my:{welcome:'KINDERLY မှ ကြိုဆိုပါသည်',title:'ကောင်းမွန်သောစောင့်ရှောက်မှုသည်<br><em>မှန်ကန်သူနှင့် စတင်သည်။</em>',side:'သင့်အခန်းကဏ္ဍကို ရွေးချယ်ပါ။',family:'ကျွန်ုပ်သည် မိသားစုဖြစ်သည်',familyTitle:'ယုံကြည်ရသော ကလေးထိန်းရှာရန်',familyText:'လိုအပ်ချက်များကို ဖော်ပြပြီး သင့်တော်သူများနှင့် တွေ့ဆုံပါ။',nanny:'ကျွန်ုပ်သည် ကလေးထိန်းဖြစ်သည်',nannyTitle:'ပရော်ဖက်ရှင်နယ်ပရိုဖိုင် တည်ဆောက်ရန်',nannyText:'အတွေ့အကြုံ၊ လိုလားချက်နှင့် အလုပ်အခြေအနေကို ဖော်ပြပါ။',switchRole:'← အခန်းကဏ္ဍပြောင်းရန်',boost:'ယုံကြည်မှုတိုးစေသော အချက်များ',boostTitle:'မိသားစုများ ယုံကြည်မှု မြန်မြန်ရစေပါ။',video:'မိတ်ဆက်ဗီဒီယို',reference:'ထောက်ခံစာ'}};
function setLanguage(code){const t=languageCopy[code]||languageCopy.en;document.documentElement.lang=code;document.querySelectorAll('.language-select').forEach(x=>x.value=code);const role=$('#roleGate');role.querySelector('.role-main>.eyebrow').textContent=t.welcome;role.querySelector('.role-main>h1').innerHTML=t.title;role.querySelector('.role-main>p:not(.eyebrow)').textContent=t.side;const cards=role.querySelectorAll('.role-options>button');cards[0].querySelector('small').textContent=t.family;cards[0].querySelector('b').textContent=t.familyTitle;cards[0].querySelector('p').textContent=t.familyText;cards[1].querySelector('small').textContent=t.nanny;cards[1].querySelector('b').textContent=t.nannyTitle;cards[1].querySelector('p').textContent=t.nannyText;$('#switchRole').textContent=t.switchRole;document.querySelector('.trust-boosters .eyebrow').textContent=t.boost;document.querySelector('.trust-boosters h3').textContent=t.boostTitle;const boosters=document.querySelectorAll('.booster-card b');boosters[0].textContent=t.video;boosters[1].textContent=t.reference;const pulseLabels={en:['Marketplace activity','AVAILABLE HELPERS','Ready to work','FAMILIES HIRING','Open roles'],zh:['市场动态','可上班的育儿帮手','正在找工作','正在招聘的家庭','开放职位'],th:['ความเคลื่อนไหว','พี่เลี้ยงที่พร้อม','พร้อมทำงาน','ครอบครัวที่กำลังจ้าง','ตำแหน่งงาน'],my:['ဈေးကွက်လှုပ်ရှားမှု','အလုပ်လုပ်နိုင်သော ကလေးထိန်းများ','အလုပ်အဆင်သင့်','အလုပ်ခန့်နေသော မိသားစုများ','အလုပ်နေရာများ']}[code]||[];const pulse=$('.market-pulse');pulse.querySelector('.pulse-heading b').textContent=pulseLabels[0];const heads=pulse.querySelectorAll('article header div');heads[0].querySelector('small').textContent=pulseLabels[1];heads[0].querySelector('b').textContent=pulseLabels[2];heads[1].querySelector('small').textContent=pulseLabels[3];heads[1].querySelector('b').textContent=pulseLabels[4];localStorage.setItem('kinderly-language',code)}
document.querySelectorAll('.language-select').forEach(x=>x.addEventListener('change',e=>setLanguage(e.target.value)));
setLanguage(localStorage.getItem('kinderly-language')||'en');
const helperActivity=[['Pim','Bangkok','6 years · Infant & toddler care','assets/pim.svg','Now'],['May','Nonthaburi','4 years · Newborn routines','assets/mali.svg','2m'],['Nok','Thong Lo','8 years · Twins & first aid','assets/nok.svg','5m'],['Thiri','Sathorn','3 years · Toddler learning','', '8m'],['Mali','On Nut','5 years · Baby-led weaning','assets/mali.svg','11m'],['Su Su','Phra Khanong','7 years · Newborn night care','', '14m']];
function renderHelperActivity(){const rows=helperActivity.concat(helperActivity);document.querySelector('.helper-ticker').innerHTML=rows.map(([name,place,skill,photo,time])=>`<div>${photo?`<img class="ticker-avatar" src="${photo}" alt="">`:'<span class="ticker-avatar default-helper-avatar">●</span>'}<p><b>${name} · ${place}</b><small>${skill}</small></p><em>${time}</em></div>`).join('')}
renderHelperActivity();
$('#timeOptions').addEventListener('click',e=>{const btn=e.target.closest('.time-option');if(!btn)return;const selected=selectedTimes();if(btn.classList.contains('selected')){if(selected.length===1){toast('Keep at least one proposed time');return}btn.classList.remove('selected')}else{if(selected.length===3){toast('Choose up to 3 times');return}btn.classList.add('selected')}});
$('#sendInviteBtn').onclick=()=>{const c=candidates[index];pendingInterview={name:c.name,times:selectedTimes(),method:document.querySelector('input[name="method"]:checked').value,email:$('#emailNotify').checked,line:$('#lineNotify').checked};$('#interviewDialog').close();addNotification(c.name);toast(`Invitation sent to ${c.name} via Kinderly${pendingInterview.line?' + LINE':''}`);setTimeout(()=>{$('#notificationPanel').hidden=false},500)};
$('#notificationBtn').onclick=()=>{$('#notificationPanel').hidden=!$('#notificationPanel').hidden;$('#notificationBtn').classList.remove('has-update')};
$('#closeNotifications').onclick=()=>{$('#notificationPanel').hidden=true};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close()}));
render();
$('#carePrompt').value=defaultPrompt;
$('#charCount').textContent=defaultPrompt.length;
